services:
  - type: web
    name: box-box-f1
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn F1.wsgi:application --log-file -
    rootDir: .              