services:
  - type: web
    name: box-box-f1
    env: python
    rootDir: src
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn F1.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
